### ISSUE TITLE
Call to undefined method Laravel\Lumen\Application::configureMonologUsing()

### ISSUE THREAD

**Issue by idan003** [aldogint/papertrail-laravel#1]
Hi, i have issue with the code when i put the code in the app.php in laravel Lumen

he give me error: Call to undefined method Laravel\Lumen\Application::configureMonologUsing()

my version: Lumen (5.6.4) (Laravel Components 5.6.*)

**Comment by aldogint** [comment]
@idan003  it seems like lumen changed the way to customize monolog in lumen 5.6.x, see https://laravel.com/docs/5.6/logging#advanced-monolog-channel-customization. I'll update readme to reflect this change.
